# ==============================| Block Glitch Fix |==============================
# A fix developed by qruet
# Show me your appreciation by buying me a coffee! https://www.paypal.me/qruet
# ================================================================================

# The plugin by default checks your server version to determine if a block fix is necessary and disables itself accordingly.
# In the latest versions of the game, Mojang has been fairly successful at removing this block issue through the client.
# If you are convinced the issue still occurs on your server but the plugin is disabling itself - set this option to True.
Override Version Check: False

# This sets for the cooldown necessary between block breaks for this plugin to begin updating nearby blocks for the player
# Smaller Number = Greater Performance
# Unit: Milliseconds
Block Break Sensitivity Cooldown: 50

# This cooldown is necessary to let the plugin's mechanics to know if the player is still actively using a tool with a high efficiency enchant.
# If they haven't been actively breaking seperate blocks under the specified BlockBreakSensitivityCooldown after this specified cooldown time
# stop updating blocks near that player. (Important for maximum performance)
# Smaller Number = Greater Performance
# Unit: Milliseconds
Block Updates Removal Cooldown: 2000

# Intervals in which blocks near the player are updated
# Larger Number = Greater Performance
# Unit: Ticks (20 = 1 second)
Block Update Interval: 5

# Block Update Radius (from player)
# Smaller Number = Improved Performance
# Unit: Blocks
Radius: 4

# Visual Bug Fix
# Reported on 1.8 clients
# This is not related to the ghost block fix but rather a visual chunk bug that occurs while
# changing worlds or connecting to the server within the first several seconds.
Chunk Visual Bug Fix: False
