name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}
description: A lightweight simple block fix to prevent players from being stuck in glitched blocks.
author: geekles